import type { Component } from 'svelte'
import {
	OurStory,
	MissionVision,
	DirectorTeam,
	AnimalEthics,
	HistoryLegacy,
	ResearchAreas,
	Publications,
	JournalOfAnimalEthics,
	ResourceLibrary,
	SummerSchools,
	UpcomingEvents,
	Conferences,
	TeachingPrograms,
	PastEventsArchive,
	MediaCommentary,
	Fellowship,
	AssociateInstitutes,
	Consultancies,
	StudentSociety,
	Volunteer,
} from '$lib/shared/utils/icons'

// Icon mapping function for navigation items
export function selectIcon(iconKey?: string | null): Component | undefined {
	if (!iconKey) return undefined

	const iconMap: Record<string, Component> = {
		OurStory: OurStory,
		MissionVision: MissionVision,
		DirectorTeam: DirectorTeam,
		AnimalEthics: AnimalEthics,
		HistoryLegacy: HistoryLegacy,
		ResearchAreas: ResearchAreas,
		Publications: Publications,
		JournalOfAnimalEthics: JournalOfAnimalEthics,
		ResourceLibrary: ResourceLibrary,
		SummerSchools: SummerSchools,
		UpcomingEvents: UpcomingEvents,
		Conferences: Conferences,
		TeachingPrograms: TeachingPrograms,
		PastEventsArchive: PastEventsArchive,
		MediaCommentary: MediaCommentary,
		Fellowship: Fellowship,
		AssociateInstitutes: AssociateInstitutes,
		Consultancies: Consultancies,
		StudentSociety: StudentSociety,
		Volunteer: Volunteer,
	}

	return iconMap[iconKey]
}

// Map page titles to icon keys based on the existing menu structure
export function getIconForPage(title: string): string | undefined {
	const titleToIconMap: Record<string, string> = {
		'Our Story': 'OurStory',
		'Mission & Vision': 'MissionVision',
		'Director & Team': 'DirectorTeam',
		'Animal Ethics': 'AnimalEthics',
		'History & Legacy': 'HistoryLegacy',
		'Research Areas': 'ResearchAreas',
		Publications: 'Publications',
		'Journal of Animal Ethics': 'JournalOfAnimalEthics',
		'Resource Library': 'ResourceLibrary',
		'Summer Schools': 'SummerSchools',
		'Upcoming Events': 'UpcomingEvents',
		Conferences: 'Conferences',
		'Teaching Programs': 'TeachingPrograms',
		'Past Events Archive': 'PastEventsArchive',
		'Media Commentary': 'MediaCommentary',
		Fellowship: 'Fellowship',
		'Associate Institutes': 'AssociateInstitutes',
		Consultancies: 'Consultancies',
		'Student Society': 'StudentSociety',
		Volunteer: 'Volunteer',
	}

	return titleToIconMap[title]
}

interface MenuItem {
	dropdownLink?: string
	hasdropdown?: boolean
	id: string
	name: string
	title: string
	label?: string
	url: string
	icon?: string
	showInNavbar?: boolean
	showInMorph?: boolean
	morph?: string
	hidedropdown?: boolean
	isVisible: boolean
	showInSitemap: boolean
	showChildren?: boolean
	children?: MenuItem[]
	subchildren?: MenuItem[]
	child?: MenuItem[]
}

const menus: MenuItem[] = [
	{
		id: 'home',
		name: 'Home',
		title: 'Home',
		label: 'Welcome to our homepage',
		url: '/home',
		isVisible: true,
		showInSitemap: true,
	},
	{
		id: 'about',
		name: 'About',
		title: 'About',
		label: 'Learn more about our organization',
		url: '/about',
		isVisible: true,
		showInNavbar: true,
		showInSitemap: true,
		showInMorph: true,
		morph: '1',
		showChildren: true,
		children: [
			{
				id: 'our-story',
				name: 'Our Story',
				title: 'Our Story',
				label: 'Read about our history and mission',
				url: '/about/our-story',
				isVisible: true,
				showInSitemap: true,
				icon: 'OurStory',
			},
			{
				id: 'mission-vision',
				name: 'Mission & Vision',
				title: 'Mission & Vision',
				label: 'Discover our goals and values',
				url: '/about/mission-vision',
				isVisible: true,
				showInSitemap: true,
				icon: 'MissionVision',
			},
			{
				id: 'director-team',
				name: 'Director & Team',
				title: 'Director & Team',
				label: 'Meet our leadership and staff',
				url: '/about/director-team',
				isVisible: true,
				showInSitemap: true,
				icon: 'DirectorTeam',
			},
			{
				id: 'animal-ethics',
				name: 'Animal Ethics',
				title: 'Animal Ethics',
				label: 'Learn about our approach to animal ethics',
				url: '/about/animal-ethics',
				isVisible: true,
				showInSitemap: true,
				icon: 'AnimalEthics',
			},
			{
				id: 'history-legacy',
				name: 'History & Legacy',
				title: 'History & Legacy',
				label: 'Explore our history and legacy',
				url: '/about/history-legacy',
				isVisible: true,
				showInSitemap: true,
				icon: 'HistoryLegacy',
			},
		],
	},
	{
		id: 'research',
		name: 'Research',
		title: 'Research',
		label: 'Discover our research initiatives',
		url: '/research',
		isVisible: true,
		showInNavbar: true,
		showInSitemap: true,
		showInMorph: true,
		morph: '1',
		showChildren: true,
		children: [
			{
				id: 'research-areas',
				name: 'Research Areas',
				title: 'Research Areas',
				label: 'Explore our areas of research focus',
				url: '/research/research-areas',
				isVisible: true,
				showInSitemap: true,
				icon: 'ResearchAreas',
			},
			{
				id: 'publications',
				name: 'Publications',
				title: 'Publications',
				label: 'Browse our publications and reports',
				url: '/research/publications',
				isVisible: true,
				showInSitemap: true,
				icon: 'Publications',
			},
			{
				id: 'journal-of-animal-ethics',
				name: 'Journal of Animal Ethics',
				title: 'Journal of Animal Ethics',
				label: 'Read our peer-reviewed journal',
				url: '/research/journal-of-animal-ethics',
				isVisible: true,
				showInSitemap: true,
				icon: 'JournalOfAnimalEthics',
			},
			{
				id: 'resource-library',
				name: 'Resource Library',
				title: 'Resource Library',
				label: 'Access our collection of resources and tools',
				url: '/research/resource-library',
				isVisible: true,
				showInSitemap: true,
				icon: 'ResourceLibrary',
			},
			{
				id: 'summer-schools',
				name: 'Summer Schools',
				title: 'Summer Schools',
				label: 'Learn about our summer school programs',
				url: '/research/summer-schools',
				isVisible: true,
				showInSitemap: true,
				icon: 'SummerSchools',
			},
		],
	},
	{
		id: 'events',
		name: 'Events',
		title: 'Events',
		label: 'Find out about our upcoming events',
		url: '/events',
		isVisible: true,
		showInNavbar: true,
		showInSitemap: true,
		showInMorph: true,
		morph: '2',
		showChildren: true,
		children: [
			{
				id: 'upcoming-events',
				name: 'Upcoming Events',
				title: 'Upcoming Events',
				label: 'See our calendar of upcoming events',
				url: '/events/upcoming-events',
				isVisible: true,
				showInSitemap: true,
				icon: 'UpcomingEvents',
			},
			{
				id: 'conferences',
				name: 'Conferences',
				title: 'Conferences',
				label: 'Learn about our conference programs',
				url: '/events/conferences',
				isVisible: true,
				showInSitemap: true,
				icon: 'Conferences',
			},
			{
				id: 'teaching-programs',
				name: 'Teaching Programs',
				title: 'Teaching Programs',
				label: 'Discover our teaching programs and courses',
				url: '/events/teaching-programs',
				isVisible: true,
				showInSitemap: true,
				icon: 'TeachingPrograms',
			},
			{
				id: 'past-events-archive',
				name: 'Past Events Archive',
				title: 'Past Events Archive',
				label: 'Browse our archive of past events',
				url: '/events/past-events-archive',
				isVisible: true,
				showInSitemap: true,
				icon: 'PastEventsArchive',
			},
			{
				id: 'media-commentary',
				name: 'Media Commentary',
				title: 'Media Commentary',
				label: 'Read our media commentary and analysis',
				url: '/events/media-commentary',
				isVisible: true,
				showInSitemap: true,
				icon: 'MediaCommentary',
			},
		],
	},
	{
		id: 'get-involved',
		name: 'Get Involved',
		title: 'Get Involved',
		label: 'Find out how you can get involved with our organization',
		url: '/get-involved',
		isVisible: true,
		showInNavbar: true,
		showInSitemap: true,
		showInMorph: true,
		morph: '2',
		showChildren: true,
		children: [
			{
				id: 'fellowship',
				name: 'Fellowship',
				title: 'Fellowship',
				label: 'Learn about our fellowship programs',
				url: '/get-involved/fellowship',
				isVisible: true,
				showInSitemap: true,
				icon: 'Fellowship',
			},
			{
				id: 'associate-institutes',
				name: 'Associate Institutes',
				title: 'Associate Institutes',
				label: 'Discover our associate institutes and partners',
				url: '/get-involved/associate-institutes',
				isVisible: true,
				showInSitemap: true,
				icon: 'AssociateInstitutes',
			},
			{
				id: 'consultancies',
				name: 'Consultancies',
				title: 'Consultancies',
				label: 'Find out about our consultancy services',
				url: '/get-involved/consultancies',
				isVisible: true,
				showInSitemap: true,
				icon: 'Consultancies',
			},
			{
				id: 'student-society',
				name: 'Student Society',
				title: 'Student Society',
				label: 'Learn about our student society and initiatives',
				url: '/get-involved/student-society',
				isVisible: true,
				showInSitemap: true,
				icon: 'StudentSociety',
			},
			{
				id: 'volunteer',
				name: 'Volunteer',
				title: 'Volunteer',
				label: 'Find out how you can volunteer with our organization',
				url: '/get-involved/volunteer',
				isVisible: true,
				showInSitemap: true,
				icon: 'Volunteer',
			},
		],
	},
	{
		id: 'support',
		name: 'Support',
		title: 'Support',
		label: 'Find out how you can support our organization',
		url: '/support',
		isVisible: true,
		showInNavbar: true,
		showInSitemap: true,
		showInMorph: true,
		morph: '3',
		showChildren: true,
		children: [
			{
				id: 'donate',
				name: 'Donate',
				title: 'Make a donation today',
				label: 'Make a donation to support our work',
				url: '/support/donate',
				isVisible: true,
				showInSitemap: true,
			},
			{
				id: 'leave-a-legacy',
				name: 'Leave a Legacy',
				title: 'Learn about leaving a legacy',
				label: 'Learn about leaving a legacy gift',
				url: '/support/leave-a-legacy',
				isVisible: true,
				showInSitemap: true,
			},
			{
				id: 'sponsor-a-project',
				name: 'Sponsor a Project',
				title: 'Find out how to sponsor',
				label: 'Find out how you can sponsor a project',
				url: '/support/sponsor-a-project',
				isVisible: true,
				showInSitemap: true,
			},
			{
				id: 'ten-year-appeal',
				name: 'Ten Year Appeal',
				title: 'Learn about our ten year appeal',
				label: 'Learn about our ten year appeal',
				url: '/support/ten-year-appeal',
				isVisible: true,
				showInSitemap: true,
			},
			{
				id: 'newsletter',
				name: 'Newsletter',
				title: 'Sign up for our newsletter',
				label: 'Sign up for our newsletter',
				url: '/support/newsletter',
				isVisible: true,
				showInSitemap: true,
			},
			{
				id: 'contact-us',
				name: 'Contact',
				title: 'Contact us for more information',
				label: 'Contact us for more information to support our work',
				url: '/support/contact-us',
				isVisible: true,
				showInSitemap: true,
			},
		],
	},
	{
		id: 'copyright',
		name: 'Copyright',
		title: 'Copyright',
		label: 'Find out how you can support our organization',
		url: '/copyright',
		isVisible: true,
		showInNavbar: false,
		showInSitemap: true,
		showInMorph: false,
		morph: '3',
		showChildren: true,
		children: [
			{
				id: 'terms-of-service',
				name: 'Terms of Service',
				title: 'View our terms of service',
				url: '/legal/terms-of-service',
				isVisible: true,
				showInSitemap: true,
			},
			{
				id: 'cookies',
				name: 'Cookies',
				title: 'View our cookie policy',
				url: '/legal/cookies',
				isVisible: true,
				showInSitemap: true,
			},
			{
				id: 'privacy',
				name: 'Privacy',
				title: 'View our privacy policy',
				url: '/legal/privacy',
				isVisible: true,
				showInSitemap: true,
			},
		],
	},
]

export { menus }
export type { MenuItem }
